### ISSUE TITLE
BLDC.sch file missing?

### ISSUE THREAD

**Issue by JorgeMaker** [BetzDrive/bldc-controller-hardware#11]
Hi, I'm trying to open your design with Kicad but it indicates that the BLDC.sch file is missing. Do you know how I can solve the problem?
![Captura de pantalla 2020-12-15 a las 19 07 21](https://user-images.githubusercontent.com/44008430/102254371-d0c82d00-3f08-11eb-92f4-d924654e62fc.png)

**Comment by gbalke** [comment]
Heya, we use the Kicad-nightly build for development. You'll have to be on the bleeding edge to view the files! I hope that's okay 🙂

**Comment by JorgeMaker** [comment]
Thank you very much for your quick answer :) I will try Kicad-nightly build.

PS: Congrats for you amazing project.  I am trying to do something very similar but using CAN instead of RS485 and  SimpleFOClibrary and I am ver interesting in learning from your project
