### ISSUE TITLE
README is missing

### ISSUE THREAD

**Issue by AlexDaniel** [BetzDrive/bldc-controller-hardware#6]
I think this project is missing a helpful README file with pictures and stuff.

By the way, is there any info available about the betz project itself? What's the goal? How does it compare to ODrive?

**Comment by gbalke** [comment]
Apologies for the delay. We're in a bit of a mix due to the current situation (difficult to access our workspace). We'll be putting together a summary of the drives and a comparison as soon as possible!

**Comment by gbalke** [comment]
@AlexDaniel looks like this got lost to the ether haha. By now I'm guessing you've picked up a controller for whatever application you were working on. I'm only just now getting some time to focus on the project again. Is there a specific use case you had in mind? I think it'd help to know if there's more information you'd like to gleam other than what I've written on [betzdrive.com](betzdrive.com).

**Comment by AlexDaniel** [comment]
It's OK, I often get notifications from tickets that I reported many years ago :)

Meanwhile I stumbled upon https://docs.simplefoc.com/ and got a compatible board (they are cheap and widely available). Still didn't get to truly use it in a project yet because I got carried away with other things, but eventually I'll get back to it.

**Comment by gbalke** [comment]
Oh that looks pretty cool! :+1:

The main motivator for this BLDC was to have an all-in-one where the encoder, thermal sensor, and IMU were co-located. Having all of these be independent systems adds to assembly complexity and additional wiring complications. I think the link I added to [Blue](https://www.berkeleyopenarms.org/) will help people understand the reasoning behind this design.

I'll close up this ticket with the hope that enough information is covered on the website :smile:.
